-- Ranking ATP individual consultado el 10 de agosto de 2026.
-- birth_date: AAAAMMDD; right_hand: 1=diestro, 0=zurdo; height: centímetros.
-- Cuando una fuente pública no proporciona un dato obligatorio: city='No consta' y valor numérico=0.
BEGIN TRANSACTION;

INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jannik', 'Sinner', 'Italia', 'San Candido', 20010816, 1, 188.0, 1, 13450);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Carlos', 'Alcaraz', 'España', 'El Palmar', 20030505, 1, 185.0, 2, 8160);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexander', 'Zverev', 'Alemania', 'Hamburgo', 19970420, 1, 198.0, 3, 8120);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Felix', 'Auger Aliassime', 'Canadá', 'Montreal', 20000808, 1, 193.0, 4, 4740);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Novak', 'Djokovic', 'Serbia', 'Belgrado', 19870522, 1, 187.0, 5, 3760);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Daniil', 'Medvedev', 'Rusia', 'Moscú', 19960211, 1, 198.0, 6, 3620);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alex', 'De Minaur', 'Australia', 'Sídney', 19990217, 1, 183.0, 7, 3560);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Taylor', 'Fritz', 'Estados Unidos', 'Rancho Santa Fe', 19971028, 1, 193.0, 8, 3400);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Flavio', 'Cobolli', 'Italia', 'Florencia', 20020506, 1, 0.0, 9, 3330);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Ben', 'Shelton', 'Estados Unidos', 'Atlanta', 20021009, 0, 0.0, 10, 2680);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexander', 'Bublik', 'Kazajistán', 'Gátchina', 19970617, 1, 198.0, 11, 2535);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jiri', 'Lehecka', 'República Checa', 'Mladá Boleslav', 20011108, 1, 183.0, 12, 2380);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Lorenzo', 'Musetti', 'Italia', 'Carrara', 20020303, 1, 185.0, 13, 2375);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Casper', 'Ruud', 'Noruega', 'Oslo', 19981222, 1, 183.0, 14, 2345);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Rafael', 'Jodar', 'España', 'Leganés', 20060917, 1, 0.0, 15, 2243);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Andrey', 'Rublev', 'Rusia', 'Moscú', 19971020, 1, 188.0, 16, 2230);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jakub', 'Mensik', 'República Checa', 'Prostějov', 20050901, 1, 0.0, 17, 2205);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Valentin', 'Vacherot', 'Mónaco', 'Rocabruna', 19981116, 1, 0.0, 18, 2176);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Learner', 'Tien', 'Estados Unidos', 'Irvine', 20051202, 0, 0.0, 19, 2155);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Frances', 'Tiafoe', 'Estados Unidos', 'Hyattsville', 19980120, 1, 188.0, 20, 2105);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Tommy', 'Paul', 'Estados Unidos', 'No consta', 19970517, 1, 185.0, 21, 2075);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Luciano', 'Darderi', 'Italia', 'Villa Gesell', 20020214, 1, 0.0, 22, 2025);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Francisco', 'Cerundolo', 'Argentina', 'Buenos Aires', 19980813, 1, 185.0, 23, 2010);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Arthur', 'Fils', 'Francia', 'Bondoufle', 20040612, 1, 0.0, 24, 1940);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alejandro', 'Davidovich Fokina', 'España', 'Málaga', 19990605, 1, 183.0, 25, 1830);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alejandro', 'Tabilo', 'Chile', 'Toronto', 19970602, 0, 188.0, 26, 1728);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Joao', 'Fonseca', 'Brasil', 'No consta', 20060821, 1, 185.0, 27, 1700);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Ugo', 'Humbert', 'Francia', 'Metz', 19980626, 0, 188.0, 28, 1625);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Arthur', 'Rinderknech', 'Francia', 'Gassin', 19950723, 1, 196.0, 29, 1623);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Tomas Martin', 'Etcheverry', 'Argentina', 'La Plata', 19990718, 1, 196.0, 30, 1510);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Brandon', 'Nakashima', 'Estados Unidos', 'San Diego', 20010803, 1, 185.0, 31, 1510);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexander', 'Blockx', 'Bélgica', 'Amberes', 20050408, 1, 0.0, 32, 1353);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Ignacio', 'Buse', 'Perú', 'Lima', 20040325, 1, 0.0, 33, 1350);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Zizou', 'Bergs', 'Bélgica', 'Lommel', 19990603, 1, 185.0, 34, 1340);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Matteo', 'Arnaldi', 'Italia', 'San Remo', 20010222, 1, 0.0, 35, 1299);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Arthur', 'Fery', 'Reino Unido', 'No consta', 20020712, 1, 0.0, 36, 1285);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Cameron', 'Norrie', 'Reino Unido', 'Johannesburgo', 19950823, 0, 188.0, 37, 1255);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Raphael', 'Collignon', 'Bélgica', 'No consta', 20020113, 1, 0.0, 38, 1234);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Karen', 'Khachanov', 'Rusia', 'Moscú', 19960521, 1, 198.0, 39, 1130);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Matteo', 'Berrettini', 'Italia', 'Roma', 19960412, 1, 196.0, 40, 1088);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jan-Lennard', 'Struff', 'Alemania', 'Warstein', 19900425, 1, 193.0, 41, 1066);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alex', 'Michelsen', 'Estados Unidos', 'Laguna Hills', 20040825, 1, 0.0, 42, 1065);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Denis', 'Shapovalov', 'Canadá', 'Tel Aviv', 19990415, 0, 185.0, 43, 1045);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Mariano', 'Navone', 'Argentina', '9 de Julio', 20010227, 1, 0.0, 44, 1030);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jaume', 'Munar', 'España', 'Santañí', 19970505, 1, 183.0, 45, 1020);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Terence', 'Atmane', 'Francia', 'Saint-Martin-Boulogne', 20020109, 0, 0.0, 46, 1007);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Adrian', 'Mannarino', 'Francia', 'Soisy-sous-Montmorency', 19880629, 0, 180.0, 47, 1005);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Sebastian', 'Baez', 'Argentina', 'Ciudad de General San Martín', 20001228, 1, 170.0, 48, 1000);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Luca', 'Van Assche', 'Francia', 'Woluwe-Saint-Lambert', 20040511, 1, 0.0, 49, 998);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Sebastian', 'Korda', 'Estados Unidos', 'Bradenton', 20000705, 1, 193.0, 50, 990);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Ethan', 'Quinn', 'Estados Unidos', 'Fresno', 20040312, 1, 0.0, 51, 989);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Juan Manuel', 'Cerundolo', 'Argentina', 'Buenos Aires', 20011115, 0, 183.0, 52, 989);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Stefanos', 'Tsitsipas', 'Grecia', 'Atenas', 19980812, 1, 193.0, 53, 980);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Quentin', 'Halys', 'Francia', 'Bondy', 19961026, 1, 191.0, 54, 980);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Nuno', 'Borges', 'Portugal', 'No consta', 19970219, 1, 185.0, 55, 970);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Roman Andres', 'Burruchaga', 'Argentina', 'Buenos Aires', 20020123, 1, 0.0, 56, 962);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Yannick', 'Hanfmann', 'Alemania', 'Karlsruhe', 19911113, 1, 193.0, 57, 961);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Tomas', 'Machac', 'República Checa', 'Beroun', 20001013, 1, 183.0, 58, 960);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Corentin', 'Moutet', 'Francia', 'Neuilly-sur-Seine', 19990419, 0, 175.0, 59, 945);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Daniel', 'Altmaier', 'Alemania', 'Kempen', 19980912, 1, 191.0, 60, 939);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Fabian', 'Marozsan', 'Hungría', 'Budapest', 19991008, 1, 0.0, 61, 930);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Miomir', 'Kecmanovic', 'Serbia', 'Belgrado', 19990831, 1, 183.0, 62, 925);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Daniel', 'Merida Aguilar', 'España', 'Madrid', 20040926, 1, 0.0, 63, 925);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Martin', 'Landaluce', 'España', 'Madrid', 20060108, 1, 0.0, 64, 920);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Thiago Agustin', 'Tirante', 'Argentina', 'La Plata', 20010410, 1, 185.0, 65, 919);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Adolfo Daniel', 'Vallejo', 'Paraguay', 'Asunción', 20040428, 1, 0.0, 66, 918);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Kamil', 'Majchrzak', 'Polonia', 'Piotrków Trybunalski', 19960113, 1, 180.0, 67, 907);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Pablo', 'Carreno-Busta', 'España', 'Gijón', 19910712, 1, 188.0, 68, 891);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Tallon', 'Griekspoor', 'Países Bajos', 'Haarlem', 19960702, 1, 188.0, 69, 885);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Botic', 'Van De Zandschulp', 'Países Bajos', 'Wageningen', 19951004, 1, 188.0, 70, 882);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Vit', 'Kopriva', 'República Checa', 'Bílovec', 19970615, 1, 178.0, 71, 868);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Hubert', 'Hurkacz', 'Polonia', 'Breslavia', 19970211, 1, 196.0, 72, 865);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Hamad', 'Medjedovic', 'Serbia', 'Novi Pazar', 20030718, 1, 0.0, 73, 844);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jenson', 'Brooksby', 'Estados Unidos', 'Sacramento', 20001026, 1, 188.0, 74, 810);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alex', 'Molcan', 'Eslovaquia', 'Prešov', 19971201, 0, 178.0, 75, 791);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Camilo', 'Ugo Carabelli', 'Argentina', 'Buenos Aires', 19990617, 1, 185.0, 76, 790);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jan', 'Choinski', 'Reino Unido', 'Coblenza', 19960610, 1, 196.0, 77, 770);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Valentin', 'Royer', 'Francia', 'Neuilly-sur-Seine', 20010529, 1, 188.0, 78, 763);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jaime', 'Faria', 'Portugal', 'Lisboa', 20030806, 1, 0.0, 79, 760);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Mattia', 'Bellucci', 'Italia', 'Busto Arsizio', 20010601, 0, 0.0, 80, 754);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Marcos', 'Giron', 'Estados Unidos', 'Thousand Oaks', 19930724, 1, 180.0, 81, 745);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Arthur', 'Gea', 'Francia', 'No consta', 20050102, 1, 180.0, 82, 744);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Marton', 'Fucsovics', 'Hungría', 'Nyíregyháza', 19920208, 1, 188.0, 83, 740);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Facundo', 'Diaz Acosta', 'Argentina', 'La Lucila', 20001215, 0, 183.0, 84, 732);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Marin', 'Cilic', 'Croacia', 'Međugorje', 19880928, 1, 198.0, 85, 721);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('James', 'Duckworth', 'Australia', 'No consta', 19920121, 1, 183.0, 86, 721);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Zachary', 'Svajda', 'Estados Unidos', 'San Diego', 20021129, 1, 175.0, 87, 719);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Lorenzo', 'Sonego', 'Italia', 'Turín', 19950511, 1, 191.0, 88, 718);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexander', 'Shevchenko', 'Kazajistán', 'No consta', 20001129, 1, 185.0, 89, 699);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Marco', 'Trungelliti', 'Argentina', 'Ciudad de Santiago del Estero', 19900131, 1, 178.0, 90, 693);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Giovanni', 'Mpetshi Perricard', 'Francia', 'Lyon', 20030708, 1, 0.0, 91, 690);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Coleman', 'Wong', 'Hong Kong', 'No consta', 20040606, 1, 0.0, 92, 680);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Rinky', 'Hijikata', 'Australia', 'Sídney', 20010223, 1, 178.0, 93, 677);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Sho', 'Shimabukuro', 'Japón', 'Gifu', 19970730, 1, 183.0, 94, 677);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Aleksandar', 'Kovacevic', 'Estados Unidos', 'Belgrado', 19980829, 1, 183.0, 95, 676);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Hugo', 'Gaston', 'Francia', 'Toulouse', 20000926, 0, 173.0, 96, 672);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Adam', 'Walton', 'Australia', 'Home Hill', 19990417, 1, 185.0, 97, 654);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Dino', 'Prizmic', 'Croacia', 'Split', 20050805, 1, 0.0, 98, 652);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Holger', 'Rune', 'Dinamarca', 'Gentofte', 20030429, 1, 185.0, 99, 650);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Martin', 'Damm', 'Estados Unidos', 'No consta', 20030930, 0, 0.0, 100, 650);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Aleksandar', 'Vukic', 'Australia', 'Sídney', 19960406, 1, 188.0, 101, 649);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Roman', 'Safiullin', 'Rusia', 'Podolsk', 19970807, 1, 185.0, 102, 648);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Benjamin', 'Bonzi', 'Francia', 'Nimes', 19960609, 1, 185.0, 103, 639);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Damir', 'Dzumhur', 'Bosnia y Herzegovina', 'Sarajevo', 19920520, 1, 175.0, 104, 632);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jesper', 'De Jong', 'Países Bajos', 'Haarlem', 20000531, 1, 180.0, 105, 618);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Emilio', 'Nava', 'Estados Unidos', 'West Hills', 20011202, 1, 183.0, 106, 604);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Francisco', 'Comesana', 'Argentina', 'Mar del Plata', 20001006, 1, 0.0, 107, 603);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Gabriel', 'Diallo', 'Canadá', 'Montreal', 20010924, 1, 0.0, 108, 595);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Toby', 'Samuel', 'Reino Unido', 'No consta', 20020906, 1, 0.0, 109, 576);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jacob', 'Fearnley', 'Reino Unido', 'Edimburgo', 20010715, 1, 0.0, 110, 574);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Dalibor', 'Svrcina', 'República Checa', 'Ostrava', 20021002, 1, 178.0, 111, 574);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Patrick', 'Kypson', 'Estados Unidos', 'Durham', 19991028, 1, 188.0, 112, 570);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Michael', 'Zheng', 'Estados Unidos', 'No consta', 20040127, 1, 0.0, 113, 565);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Otto', 'Virtanen', 'Finlandia', 'Hyvinkää', 20010621, 1, 0.0, 114, 564);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Eliot', 'Spizzirri', 'Estados Unidos', 'Greenwich', 20011223, 1, 0.0, 115, 557);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Yibing', 'Wu', 'China', 'Hangzhou', 19991014, 1, 183.0, 116, 553);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Shintaro', 'Mochizuki', 'Japón', 'Kawasaki', 20030602, 1, 0.0, 117, 547);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Bu', 'Yunchaokete', 'China', 'Prefectura autónoma mongol de Bortala', 20020119, 1, 0.0, 118, 546);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Titouan', 'Droguet', 'Francia', 'Villeneuve-Saint-Georges', 20010615, 1, 0.0, 119, 532);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Vilius', 'Gaubas', 'Lituania', 'Šiauliai', 20041229, 1, 0.0, 120, 523);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Kyrian', 'Jacquet', 'Francia', 'Lyon', 20010511, 1, 175.0, 121, 521);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Dane', 'Sweeny', 'Australia', 'Penrith', 20010212, 1, 170.0, 122, 518);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Zsombor', 'Piros', 'Hungría', 'Budapest', 19991013, 1, 180.0, 123, 517);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Stan', 'Wawrinka', 'Suiza', 'Lausana', 19850328, 1, 182.0, 124, 513);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Henrique', 'Rocha', 'Portugal', 'Oporto', 20040406, 1, 0.0, 125, 509);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Sebastian', 'Ofner', 'Austria', 'Bruck an der Mur', 19960512, 1, 191.0, 126, 505);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Pablo', 'Llamas Ruiz', 'España', 'No consta', 20021013, 1, 0.0, 127, 489);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Leandro', 'Riedi', 'Suiza', 'Frauenfeld', 20020127, 1, 0.0, 128, 487);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Nicolas', 'Mejia', 'Colombia', 'Bogotá', 20000211, 1, 185.0, 129, 485);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Nikoloz', 'Basilashvili', 'Georgia', 'Tiflis', 19920223, 1, 185.0, 130, 482);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Gustavo', 'Heide', 'Brasil', 'No consta', 20020228, 1, 0.0, 131, 474);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jurij', 'Rodionov', 'Austria', 'Núremberg', 19990516, 0, 191.0, 132, 463);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Christopher', 'O''Connell', 'Australia', 'Sídney', 19940603, 1, 183.0, 133, 461);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Andrea', 'Pellegrino', 'Italia', 'Bisceglie', 19970323, 1, 185.0, 134, 454);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexandre', 'Muller', 'Francia', 'Poissy', 19970201, 1, 183.0, 135, 445);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Cristian', 'Garin', 'Chile', 'Arica', 19960530, 1, 185.0, 136, 438);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Grigor', 'Dimitrov', 'Bulgaria', 'Haskovo', 19910516, 1, 191.0, 137, 432);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Arthur', 'Cazaux', 'Francia', 'Montpellier', 20020823, 1, 0.0, 138, 432);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Alexei', 'Popyrin', 'Australia', 'Sídney', 19990805, 1, 196.0, 139, 430);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Stefano', 'Travaglia', 'Italia', 'Ascoli Piceno', 19911228, 1, 185.0, 140, 429);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Hugo', 'Dellien', 'Bolivia', 'Santa Cruz de la Sierra', 19930616, 1, 180.0, 141, 426);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Reilly', 'Opelka', 'Estados Unidos', 'St. Joseph', 19970828, 1, 211.0, 142, 421);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Jack', 'Draper', 'Reino Unido', 'Londres', 20011222, 0, 191.0, 143, 410);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Mackenzie', 'McDonald', 'Estados Unidos', 'Berkeley', 19950416, 1, 178.0, 144, 405);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Marcelo Tomas', 'Barrios Vera', 'Chile', 'Chillán', 19971210, 1, 191.0, 145, 400);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Nishesh', 'Basavareddy', 'Estados Unidos', 'Newport Beach', 20050502, 1, 0.0, 146, 399);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Timofey', 'Skatov', 'Kazajistán', 'Petropavl', 20010121, 1, 173.0, 147, 391);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Pedro', 'Martinez', 'España', 'Manoguayabo', 19970426, 1, 185.0, 148, 386);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Dusan', 'Lajovic', 'Serbia', 'Belgrado', 19900630, 1, 183.0, 149, 378);
INSERT INTO TENNIS_PLAYERS (name, surname, country, city, birth_date, right_hand, height, ranking, points) VALUES ('Chris', 'Rodesch', 'Luxemburgo', 'Angelsberg', 20010718, 1, 0.0, 150, 377);

COMMIT;
