BEGIN TRANSACTION;

INSERT INTO TOURNAMENTS (name, points, surface, city, country) VALUES
('Australian Open', 2000, 'Hard', 'Melbourne', 'Australia'),
('Roland Garros', 2000, 'Clay', 'París', 'Francia'),
('Wimbledon', 2000, 'Grass', 'Londres', 'Reino Unido'),
('US Open', 2000, 'Hard', 'Nueva York', 'Estados Unidos'),
('Indian Wells Open', 1000, 'Hard', 'Indian Wells', 'Estados Unidos'),
('Miami Open', 1000, 'Hard', 'Miami Gardens', 'Estados Unidos'),
('Monte-Carlo Masters', 1000, 'Clay', 'Roquebrune-Cap-Martin', 'Francia'),
('Mutua Madrid Open', 1000, 'Clay', 'Madrid', 'España'),
('Internazionali BNL d''Italia', 1000, 'Clay', 'Roma', 'Italia'),
('Canadian Open', 1000, 'Hard', 'Toronto / Montreal', 'Canadá'),
('Cincinnati Open', 1000, 'Hard', 'Mason, Ohio', 'Estados Unidos'),
('Shanghai Masters', 1000, 'Hard', 'Shanghái', 'China'),
('Rolex Paris Masters', 1000, 'Hard', 'Nanterre', 'Francia'),
('Dallas Open', 500, 'Hard', 'Frisco, Texas', 'Estados Unidos'),
('ABN AMRO Open', 500, 'Hard', 'Rotterdam', 'Países Bajos'),
('Qatar ExxonMobil Open', 500, 'Hard', 'Doha', 'Catar'),
('Rio Open', 500, 'Clay', 'Río de Janeiro', 'Brasil'),
('Abierto Mexicano Telcel', 500, 'Hard', 'Acapulco', 'México'),
('Dubai Duty Free Tennis Championships', 500, 'Hard', 'Dubái', 'Emiratos Árabes Unidos'),
('Barcelona Open Banc Sabadell', 500, 'Clay', 'Barcelona', 'España'),
('BMW Open', 500, 'Clay', 'Múnich', 'Alemania'),
('Bitpanda Hamburg Open', 500, 'Clay', 'Hamburgo', 'Alemania'),
('Terra Wortmann Open', 500, 'Grass', 'Halle (Westfalia)', 'Alemania'),
('HSBC Championships', 500, 'Grass', 'Londres', 'Reino Unido'),
('Mubadala Citi DC Open', 500, 'Hard', 'Washington D. C.', 'Estados Unidos'),
('China Open', 500, 'Hard', 'Pekín', 'China'),
('Japan Open', 500, 'Hard', 'Tokio', 'Japón'),
('Swiss Indoors Basel', 500, 'Hard', 'Basilea', 'Suiza'),
('Erste Bank Open', 500, 'Hard', 'Viena', 'Austria'),
('Brisbane International', 250, 'Hard', 'Tennyson (Brisbane)', 'Australia'),
('Hong Kong Open', 250, 'Hard', 'Hong Kong', 'Hong Kong'),
('Adelaide International', 250, 'Hard', 'North Adelaide', 'Australia'),
('ASB Classic', 250, 'Hard', 'Parnell (Auckland)', 'Nueva Zelanda'),
('Open Occitanie', 250, 'Hard', 'Pérols (Montpellier)', 'Francia'),
('IEB+ Argentina Open', 250, 'Clay', 'Palermo (Buenos Aires)', 'Argentina'),
('Delray Beach Open', 250, 'Hard', 'Delray Beach, Florida', 'Estados Unidos'),
('Open 13 Provence', 250, 'Hard', 'Marsella', 'Francia'),
('Chile Open', 250, 'Clay', 'Las Condes (Santiago)', 'Chile'),
('Grand Prix Hassan II', 250, 'Clay', 'Marrakech', 'Marruecos'),
('Tiriac Open', 250, 'Clay', 'Bucarest', 'Rumanía'),
('U.S. Men''s Clay Court Championship', 250, 'Clay', 'Houston, Texas', 'Estados Unidos'),
('Gonet Geneva Open', 250, 'Clay', 'Ginebra', 'Suiza'),
('BOSS Open', 250, 'Grass', 'Stuttgart', 'Alemania'),
('Libema Open', 250, 'Grass', 'Rosmalen (''s-Hertogenbosch)', 'Países Bajos'),
('Mallorca Championships', 250, 'Grass', 'Santa Ponça (Mallorca)', 'España'),
('Eastbourne Open', 250, 'Grass', 'Eastbourne', 'Reino Unido'),
('Nordea Open', 250, 'Clay', 'Båstad', 'Suecia'),
('EFG Swiss Open Gstaad', 250, 'Clay', 'Gstaad', 'Suiza'),
('Plava Laguna Croatia Open Umag', 250, 'Clay', 'Umag', 'Croacia'),
('Generali Open Kitzbühel', 250, 'Clay', 'Kitzbühel', 'Austria'),
('Millennium Estoril Open', 250, 'Clay', 'Estoril (Cascais)', 'Portugal'),
('Los Cabos Open', 250, 'Hard', 'San José del Cabo', 'México'),
('Winston-Salem Open', 250, 'Hard', 'Winston-Salem, Carolina del Norte', 'Estados Unidos'),
('Moselle Open', 250, 'Hard', 'Metz', 'Francia'),
('Chengdu Open', 250, 'Hard', 'Chengdu', 'China'),
('European Open', 250, 'Hard', 'Amberes', 'Bélgica'),
('BNP Paribas Nordic Open', 250, 'Hard', 'Estocolmo', 'Suecia'),
('Belgrade Open', 250, 'Hard', 'Belgrado', 'Serbia'),
('Hangzhou Open', 250, 'Hard', 'Hangzhou', 'China');

COMMIT;
